# Generated by Django 3.2 on 2022-02-09 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='anapath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anapath', models.FileField(upload_to='media/')),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField()),
                ('nb_vues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='anatomie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anatomie', models.FileField(upload_to='media/')),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('nb_vues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='biologie_clinique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioclinique', models.FileField(upload_to='media/')),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('nb_vues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='embryologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embryologie', models.FileField(upload_to='media/')),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('nb_vues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='immunologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immunologie', models.FileField(upload_to='media/')),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('nb_vues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='microbiologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microbiologie', models.FileField(upload_to='media/')),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('nb_vues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='parasito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parasito', models.FileField(upload_to='media/')),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('nb_vues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacologie', models.FileField(upload_to='media/')),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('nb_vues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='physio_speciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physio_speciale', models.FileField(upload_to='media/')),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('nb_vues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='physiopathologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physiopathologie', models.FileField(upload_to='media/')),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('nb_vues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='radiologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiologie', models.FileField(upload_to='media/')),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('nb_vues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='comment_radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comments', 'pub_date')},
            },
        ),
        migrations.CreateModel(
            name='comment_physios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comments', 'pub_date')},
            },
        ),
        migrations.CreateModel(
            name='comment_physio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comments', 'pub_date')},
            },
        ),
        migrations.CreateModel(
            name='comment_pharm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comments', 'pub_date')},
            },
        ),
        migrations.CreateModel(
            name='comment_parasito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comments', 'pub_date')},
            },
        ),
        migrations.CreateModel(
            name='comment_micro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comments', 'pub_date')},
            },
        ),
        migrations.CreateModel(
            name='comment_immuno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comments', 'pub_date')},
            },
        ),
        migrations.CreateModel(
            name='comment_embryo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comments', 'pub_date')},
            },
        ),
        migrations.CreateModel(
            name='comment_biocli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comments', 'pub_date')},
            },
        ),
        migrations.CreateModel(
            name='comment_anat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comments', 'pub_date')},
            },
        ),
        migrations.CreateModel(
            name='comment_anap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(default='')),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comments')},
            },
        ),
    ]
